▲리스트4.10 : NumPy를 사용해서 행렬 곱을 계산한다

In [1]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


▲리스트4.11 : NumPy를 사용해 요소별 곱을 계산한다

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


#### □문제
　리스트4.12에서 행렬a와 행렬b의 행렬곱, 행렬c와 행렬d의 요소별 곱을 구합시다.

▲리스트4.12 : 문제

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 행렬 곱



c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 행렬별 곱


#### □정답 예

▲리스트4.13 : 정답 예

In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 행렬 곱
print(np.dot(a, b))
      
print()

c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 요소별 곱
print(c*d)

[[ 5  8]
 [ 8 14]]

[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
