▲리스트4.14 : 행렬을 전치한다

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 행렬

print(a.T)  # 전치

[[1 4]
 [2 5]
 [3 6]]


▲리스트4.15 : 전치한 후 행렬곱을 실시한다

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])  # 2×3의 행렬
b = np.array([[0, 1, 2],
             [1, 2, 3]])  # 2×3의 행렬 이대로는 행렬곱을 할 수 없다

# print(np.dot(a, b))  # 전치하지 않고 행렬곱을 취하면 에러
print(np.dot(a, b.T))  # 전치에 의해 행렬곱이 가능으로

[[ 5  8]
 [ 8 14]]


#### □문제
　리스트4.16에서 행렬a 또는 행렬b를 전치하고, 행렬a와 행렬b의 행렬곱을 계산합시다.

▲리스트4.16 : 문제

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 행렬곱



#### □정답 예

▲리스트4.17：정답 예

In [5]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 행렬곱
print(np.dot(a, b.T))

[[ 5 11]
 [ 8 20]]
